copyright: Copyright &copy; 2024 qwrtln
site_name: Painting minis of Heroes of Might and Magic III
site_url: https://paint-h3.qwrtln.nl/
site_dir: gh_pages
docs_dir: docs

theme:
  name: material
  favicon: null
  logo: assets/palette.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: defaultfavicon.ico
      primary: green
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
  - blog:
      blog_dir: .
      blog_toc: true
      categories_name: Categories
      post_url_format: "blog/{date}/{slug}"
      post_url_date_format: yyyy/MM
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: KumoCorp
      repo: kumomta
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - assets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - style.css

nav:
  - "Home": index.md
  - "Contact": contact.md
