name: Publish localized site
on:
  push:
    branches:
      - main

jobs:
  localize:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: pl
            secret_name: SSH_DEPLOY_KEY_PL
            site_description: "Malowanie figurek Heroes of Might and Magic III"
          - language: ru
            secret_name: SSH_DEPLOY_KEY_RU
            site_description: "Раскраска миниатюр из Героев Меча и Магии III"

    steps:
      - uses: actions/checkout@v4

      - name: Set site language
        run: |
          sed -i -e 's/language: en/language: ${{ matrix.language }}/' \
                 -e 's@site_url: https://paint-h3.qwrtln.nl/@site_url: https://${{ matrix.language }}.paint-h3.qwrtln.nl/@' \
                 -e 's/Painting minis of Heroes of Might and Magic III: The Board Game/${{ matrix.site_description }}/' \
                 -e 's/gb-round/${{ matrix.language }}-round/' \
            mkdocs.yml

      - name: Set localization language
        run: |
          sed -i 's/pl ru/${{ matrix.language }}/' po4a.cfg

      - name: Generate ${{ matrix.language }} translations
        uses: qwrtln/po4a-action@v1
        with:
          version: "0.73"
          config: "po4a.cfg"
          args: "--no-update"

      - name: Replace files with localized ones
        run: |
          for file in $(find docs/ -name "*${{ matrix.language }}.md"); do
            echo "Moving file: $file -> ${file::-5}md"
            mv "$file" "${file::-5}md"
          done

      - name: Localize comments
        run: |
          mv overrides/partials/${{ matrix.language }}/comments.html overrides/partials/comments.html
          rm -rf overrides/partials/pl overrides/partials/ru

      - name: Set CNAME for ${{ matrix.language }}
        run: |
          echo "${{ matrix.language }}.$(cat docs/CNAME)" > docs/CNAME

      - name: Create dir for publishing
        run: |
          mkdir -p ${{ matrix.language }}/.github/workflows
          cp .github/workflows/publish-docs.yml ${{ matrix.language }}/.github/workflows
          cp -r overrides docs mkdocs.yml ${{ matrix.language }}

      - name: Push ${{ matrix.language }} site
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets[matrix.secret_name] }}
          external_repository: qwrtln/homm3bg-painting.${{ matrix.language }}
          full_commit_message: ${{ github.event.head_commit.message }}
          publish_branch: main
          force_orphan: true
          publish_dir: ${{ matrix.language }}
          exclude_assets: ''
