name: Publish localized site
on:
  push:
    branches:
      - main
env:
  PO4A_VERSION: "0.73"
  PO4A_GH_URL: https://github.com/mquinson/po4a/releases/download

jobs:
  localize:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: pl
            secret_name: SSH_DEPLOY_KEY_PL
            site_description: "Malowanie figurek Heroes of Might and Magic III"
          - language: ru
            secret_name: SSH_DEPLOY_KEY_RU
            site_description: "Раскраска миниатюр из Героев Меча и Магии III"

    steps:
      - uses: actions/checkout@v4

      - name: Set site language
        run: |
          sed -i -e 's/language: en/language: ${{ matrix.language }}/' \
                 -e 's@site_url: https://paint-h3.qwrtln.nl/@site_url: https://${{ matrix.language }}.paint-h3.qwrtln.nl/@' \
                 -e 's/Painting minis of Heroes of Might and Magic III: The Board Game/${{ matrix.site_description }}/' \
                 -e 's/gb-round/${{ matrix.language }}-round/' \
            mkdocs.yml

      - name: Set localization language
        run: |
          sed -i 's/pl ru/${{ matrix.language }}/' po4a.cfg

      - name: Set site URL
        run: |
          sed -i 's@site_url: https://paint-h3.qwrtln.nl/@@' mkdocs.yml

      - name: Install po4a
        run: |
          sudo apt-get -q install -y po4a libsyntax-keyword-try-perl  # required as standalone po4a is missing some deps
          wget --quiet ${{ env.PO4A_GH_URL }}/v${{ env.PO4A_VERSION }}/po4a-${{ env.PO4A_VERSION}}.tar.gz  # sadly the version from apt isn't working
          export PO4A_DIR="po4a-${{ env.PO4A_VERSION }}"
          tar -xf ${PO4A_DIR}.tar.gz

      - name: Generate ${{ matrix.language }} translations
        run: |
          export PO4A_DIR="po4a-${{ env.PO4A_VERSION }}"
          export PERL5LIB="${PO4A_DIR}/lib:${PERL5LIB}"
          ./${PO4A_DIR}/po4a --no-update po4a.cfg
          rm -rf ${PO4A_DIR}
          rm  ${PO4A_DIR}.tar.gz

      - name: Replace files with localized ones
        run: |
          for file in $(find docs/ -name "*${{ matrix.language }}.md"); do
            echo "Moving file: $file -> ${file::-5}md"
            mv "$file" "${file::-5}md"
          done

      - name: Set CNAME for ${{ matrix.language }}
        run: |
          echo "${{ matrix.language }}.$(cat docs/CNAME)" > docs/CNAME

      - name: Create dir for publishing
        run: |
          mkdir -p ${{ matrix.language }}/.github/workflows
          cp .github/workflows/publish-docs.yml ${{ matrix.language }}/.github/workflows
          cp -r overrides docs mkdocs.yml ${{ matrix.language }}

      - name: Push ${{ matrix.language }} site
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets[matrix.secret_name] }}
          external_repository: qwrtln/homm3bg-painting.${{ matrix.language }}
          full_commit_message: ${{ github.event.head_commit.message }}
          publish_branch: main
          force_orphan: true
          publish_dir: ${{ matrix.language }}
          exclude_assets: ''
